import React from 'react';
import Header from '../Header/Header';
import "./PrivacyPolicy.css"

function PrivacyPolicy() {
  return (

    <div className='Privacy-Policy d-flex flex-column'>
      <Header />
      <div className='container d-flex flex-column justify-content-center align-items-center h-100'>
        <div className='row align-items-center gy-4'>
          <div className='col-lg-6 text-center'> {/* Added text-center class to center the text */}
            <div className='text-content'>
              <h1 className='body-heading my-5'>
                Privacy <span className='color-yellow'>Policy</span>
              </h1>
              <p className='body-paragraph main'>
                Last updated: May 28, 2024
              </p>
              <p className='para'>
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

              </p>
              <h2 className='body-heading my-4'>
                Interpretation and Definitions
              </h2>
              <p className='body-paragraph main'>
                Interpretation

              </p>
              <p className='para'>
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

              </p>
              <p className='body-paragraph main'>
                Definitions
              </p>
              <p className='body-paragraph'>For the purposes of this Privacy Policy:</p>
              <p className='body-paragraph'>Account means a unique account created for You to access our Service or parts of our Service.</p>
              <p className='body-paragraph'>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
              <p className='body-paragraph'>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Creative FUSION, 3rd Floor, Al-Ahmed plaze, Block 13-C, Gulshan-e-Iqbal, Karachi.</p>
              <p className='body-paragraph'>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
              <p className='body-paragraph'>Country refers to: Pakistan & Canada</p>
              <p className='body-paragraph'>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
              <p className='body-paragraph'>Personal Data is any information that relates to an identified or identifiable individual.</p>
              <p className='body-paragraph'>Service refers to the Website.</p>
              <p className='body-paragraph'>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>

              <p className='body-paragraph'>Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
              <p className='body-paragraph'>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
              <p className='body-paragraph'>Website refers to Creative FUSION, accessible from Creativefusion.com</p>
              <p className='body-paragraph'>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>

              <h2 className='body-heading my-4'>
                Collecting and Using Your Personal Data
              </h2>

              <p className='body-paragraph main'>
                Types of Data Collected
              </p>
              <p className='body-paragraph main'>
                Personal Data
              </p>

              <p className='body-paragraph'>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.Personally identifiable information may include, but is not limited to: <br></br>
                Email address <br></br>
                First name and last name<br></br>
                Phone number<br></br>
                Usage Data<br></br>
              </p>

              <p className='body-paragraph main'>
                Usage Data
              </p>

              <p className='body-paragraph'>Usage Data is collected automatically when using the Service.<br></br>
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br></br>
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.<br></br>
                We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
              </p>

              <p className='body-paragraph main'>
                Information from Third-Party Social Media Services
              </p>
              <p className='body-paragraph'>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:<br></br>
                ·         Google<br></br>
                ·         Facebook<br></br>
                ·         Instagram<br></br>
                ·         Twitter<br></br>
                ·         LinkedIn<br></br>
                If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.<br></br>
                You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.
              </p>
              <p className='body-paragraph main'>
                Tracking Technologies and Cookies
              </p>

              <p className='body-paragraph'>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>

              <p className='body-paragraph main'>
              Cookies or Browser Cookies
              </p>

              <p className='body-paragraph'>A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</p>





            </div>
          </div>
        </div>
      </div>
    </div>

  )
}

export default PrivacyPolicy;